---
- name: discourse | fetch from git
  git: repo=${discourse_repo}
       version=${discourse_commit}
       dest=/home/discourse/discourse
  register: git_repo

- name: discourse | set file permissions
  file: path=/home/discourse/discourse
        state=directory
        recurse=yes
        owner=discourse
        group=discourse

- name: discourse | copy config/database.yml
  template: src=database.yml
            dest=/home/discourse/discourse/config/database.yml
            owner=discourse
            group=discourse

- name: discourse | copy config/redis.yml
  template: src=redis.yml
            dest=/home/discourse/discourse/config/redis.yml
            owner=discourse
            group=discourse

- name: discourse | copy config/environments/production.rb
  template: src=production.rb
            dest=/home/discourse/discourse/config/environments/production.rb
            owner=discourse
            group=discourse

- name: discourse | create pids and sockets directories
  file: name=/home/discourse/$item
        state=directory
        owner=discourse
        group=discourse
  with_items:
  - pids
  - sockets
  - log

- name: discourse | loading seed data
  command: /bin/su - discourse -c "cd /home/discourse/discourse && psql discourse_production < pg_dumps/production-image.sql"
  only_if: ${load_seed_data}

- name: discourse | copy plugins
  sudo: no
  local_action: command rsync -e ssh -a --delete roles/discourse/files/plugins root@{{inventory_hostname}}:/home/discourse/discourse

- name: discourse | set plugins permissions
  file: path=/home/discourse/discourse/plugins
        state=directory
        recurse=yes
        owner=discourse
        group=discourse

- name: discourse | bundle install
  command: /bin/bash --login -c "cd /home/discourse/discourse && bundle install --deployment --without test"
  only_if: ${git_repo.changed}

- name: discourse | precompile assets
  command: /bin/bash --login -c "cd /home/discourse/discourse && RUBY_GC_MALLOC_LIMIT={{ruby_gc_malloc_limit}} RAILS_ENV=production bundle exec rake assets:precompile"

- name: discourse | migrate database
  command: /bin/bash --login -c "cd /home/discourse/discourse && RUBY_GC_MALLOC_LIMIT={{ruby_gc_malloc_limit}} RAILS_ENV=production bundle exec rake db:migrate"

- name: discourse | copy monit config
  template: src=monit
            dest=/etc/monit/conf.d/discourse
  register: discourse_monit_config

- name: discourse | restart monit
  service: name=monit state=restarted
  only_if: ${discourse_monit_config.changed}

- name: discourse | restart application
  shell: monit -g discourse restart
