- name: Add New Relic apt repository
  get_url: dest=/etc/apt/sources.list.d/newrelic.list url=http://download.newrelic.com/debian/newrelic.list
  register: new_relic_repo

- name: Add New Relic key
  shell: apt-key adv --keyserver hkp://subkeys.pgp.net --recv-keys 548C16BF
  only_if: ${new_relic_repo.changed}

- name: Update apt cache
  apt: update_cache=yes
  only_if: ${new_relic_repo.changed}

- name: Install server monitor daemon
  apt: pkg=newrelic-sysmond state=present

- name: Add license key
  shell: nrsysmond-config --set license_key={{newrelic_license_key}}

- name: Start sysmond service
  service: name=newrelic-sysmond state=started

